(()=>{
const main=document.querySelector('main'),welcome=document.querySelector('.welcome');
const nav=document.createElement('nav');nav.className='tabs';nav.innerHTML='<button class="tab active" data-page="policies">POLICY LIBRARY</button><button class="tab" data-page="guide">RULING & STANDING GUIDE</button>';welcome.after(nav);
const policyPage=document.createElement('div');policyPage.id='policiesPage';policyPage.className='tabPage active';while(nav.nextSibling)policyPage.appendChild(nav.nextSibling);nav.after(policyPage);
const guide=document.createElement('section');guide.id='guidePage';guide.className='tabPage';guide.innerHTML=`
<div class="guidePanel"><h2>V-Points Ruling & Standing Guide</h2><p>Every employee starts with <b>100 points</b>. Points guide recognition, coaching, monitoring, and management review. They do not automatically create a final penalty.</p><div class="standingGrid">
<div class="standing"><b>200+ · Exceptional Performer</b>Special recognition, certificate, reward consideration, and promotion or leadership assessment.</div><div class="standing"><b>150–199 · Outstanding</b>Certificate, management commendation, and priority for training or leadership opportunities.</div><div class="standing"><b>120–149 · Very Good</b>Positive recognition and possible merit reward.</div><div class="standing"><b>100–119 · Good Standing</b>Meets company expectations.</div><div class="standing"><b>95–99 · Needs Guidance</b>Documented verbal coaching.</div><div class="standing"><b>90–94 · For Monitoring</b>Written coaching and 30-day improvement plan.</div><div class="standing"><b>80–89 · Performance Review</b>Formal appraisal, improvement plan, monitoring, and NTE when supported by a specific violation.</div><div class="standing"><b>Below 80 · Management Case Review</b>HR and management review of the complete record. This is not automatic termination.</div></div>
<div class="legalBox"><b>Important:</b> No employee will be suspended or terminated based only on a V-Points total. Any disciplinary decision must be based on a specific proven offense, reliable evidence, proportionality, employee explanation, proper approval, and lawful due process. Merit points cannot erase or cancel a serious pending case.</div>
<h3>Demerit and Merit Rules</h3><p><b>Demerit:</b> Only an approved VARDA ACT report may deduct points. No Proof, No Point. Minor: 1–4; Major: 5–14; Critical: 15–25.</p><p><b>Merit:</b> Leader commendation +2 to +5; completed special mission +2 to +5; internal certificate +1 to +2; relevant external certificate +3 to +5; upper-management commendation +5 to +10; outstanding approved appraisal +10; exceeds-expectations appraisal +5. The same achievement or violation must not be counted twice.</p></div>
<div class="ackPanel"><h2>Employee Policy Acknowledgment</h2><p>I acknowledge that I received access to the VARDA Company Policy and V-Points Standing Guide, had the opportunity to read them in English or Tagalog, and understand that I am expected to follow all lawful and properly communicated company policies. My acknowledgment confirms receipt and understanding; it does not waive any right provided by law.</p>
<form id="ackForm"><div class="ackGrid"><label>Complete Name<input id="ackName" required autocomplete="name"></label><label>Employee ID<input id="ackId" required></label><label>Branch<select id="ackBranch" required><option value="">Select branch</option><option>DLSL Food Park</option><option>Ateneo 2GONZ</option><option>Mapua Davao Food Hall</option><option>LPU Main Batangas</option><option>LPU Lima Maritime</option><option>PUP Manila</option><option>St. Jude</option><option>National Branch</option></select></label><label>Position<input id="ackPosition" required></label><label class="full">E-Signature<div class="signatureWrap"><canvas id="signature" aria-label="Signature pad"></canvas><div class="sigActions"><span>Sign using finger or mouse</span><button class="smallBtn" id="clearSig" type="button">Clear</button></div></div></label><label class="full">Selfie Verification<input id="selfie" type="file" accept="image/*" capture="user" required><img id="selfiePreview" class="selfiePreview" alt="Selfie preview"></label></div>
<div class="privacy"><b>Privacy Notice:</b> Your name, employee ID, branch, position, signature, selfie, timestamp, and acknowledged policy version will be collected only to verify policy receipt and identity. Records will be accessible only to authorized Varda HR/Retail Management, stored in a restricted company Drive folder, retained according to the approved employee-record retention schedule, and securely deleted when no longer required. Contact Varda’s authorized privacy/HR representative for access or correction requests.</div>
<div class="checks"><label><input id="readCheck" type="checkbox" required> I confirm that I reviewed the Policy Library and Ruling & Standing Guide and had an opportunity to ask questions.</label><label><input id="privacyCheck" type="checkbox" required> I have read the Privacy Notice and understand how my acknowledgment data will be processed.</label></div><button class="submitAck" type="submit">SUBMIT ACKNOWLEDGMENT</button><div class="ackStatus" id="ackStatus">Secure Drive submission will activate after the company Google Drive connection is completed.</div></form></div>`;main.appendChild(guide);
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));policyPage.classList.toggle('active',b.dataset.page==='policies');guide.classList.toggle('active',b.dataset.page==='guide');scrollTo({top:welcome.offsetTop,behavior:'smooth'});}));
const canvas=document.getElementById('signature'),ctx=canvas.getContext('2d');let drawing=false,signed=false;function sizePad(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=180*d;ctx.scale(d,d);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#17212b'}sizePad();function point(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:p.clientX-r.left,y:p.clientY-r.top}}function start(e){drawing=true;signed=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function move(e){if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function stop(){drawing=false}['mousedown','touchstart'].forEach(x=>canvas.addEventListener(x,start,{passive:false}));['mousemove','touchmove'].forEach(x=>canvas.addEventListener(x,move,{passive:false}));['mouseup','mouseleave','touchend'].forEach(x=>canvas.addEventListener(x,stop));document.getElementById('clearSig').addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false});document.getElementById('selfie').addEventListener('change',e=>{const f=e.target.files[0],img=document.getElementById('selfiePreview');if(f){img.src=URL.createObjectURL(f);img.style.display='block'}});document.getElementById('ackForm').addEventListener('submit',e=>{e.preventDefault();const status=document.getElementById('ackStatus');if(!signed){status.textContent='Please provide your e-signature before submitting.';return}status.textContent='Submission is not yet connected. Authorized management must first connect the secure company Google Drive destination.'});
})();
