window.VARDA_TL={
'VARDA ACT-001':{title:'Pagtulog o Pagpapabaya Habang Naka-duty',rule:'Pagtulog, sinasadyang pagpapahinga, o paglalaboy sa oras ng bayad na trabaho sa halip na gampanan ang nakatalagang tungkulin.'},
'VARDA ACT-002':{title:'Pag-iwan sa Nakatalagang Puwesto',rule:'Pag-alis sa puwesto, counter, kusina, cashier, o service area nang walang pahintulot o maayos na turnover.'},
'VARDA ACT-003':{title:'Pagsuway o Pagtanggi sa Makatwirang Utos sa Trabaho',rule:'Pagtanggi sa legal at makatwirang utos ng awtorisadong supervisor o manager tungkol sa operasyon, kalinisan, serbisyo, o food safety.'},
'VARDA ACT-004':{title:'Hindi Magalang na Asal',rule:'Bastos, mapanlait, nananakot, diskriminasyon, o hindi propesyonal na asal sa katrabaho, customer, o komunidad ng paaralan.'},
'VARDA ACT-005':{title:'Pandaraya, Pamemeke, o Maling Ulat',rule:'Maling pahayag o time log, pekeng completion report, minanipulang ebidensya, o sinasadyang maling impormasyon sa V-SCORE o operational records.'},
'VARDA ACT-006':{title:'Hindi Pagkilala sa Kinakailangang Memo',rule:'Hindi pagbasa o pagkilala sa mandatory company memo sa loob ng itinakdang panahon kahit may sapat na access.'},
'VARDA ACT-007':{title:'Pagkahuli o Hindi Handa sa Oras ng Shift',rule:'Pagdating nang late o hindi pagiging handa sa puwesto sa takdang opening o shift nang walang valid na dahilan.'},
'VARDA ACT-008':{title:'Hindi Awtorisadong Pagliban / No Call No Show',rule:'Pagliban nang walang paunang abiso o pahintulot na nakaaapekto sa manpower at tuloy-tuloy na serbisyo.'},
'VARDA ACT-009':{title:'Hindi Maayos o Kulang na Turnover',rule:'Hindi pag-endorso ng cash, logs, inventory, incident details, pending customer concerns, o kalagayan ng station sa susunod na shift.'},
'VARDA ACT-010':{title:'Paulit-ulit na Minor Violation sa Loob ng 30 Araw',rule:'Tatlo o higit pang minor violation sa gumugulong na 30 araw na nagpapakita ng tuloy-tuloy na hindi pagsunod.'},
'VARDA ACT-011':{title:'Walang Hairnet, Cap, o Hair Restraint',rule:'Pag-handle ng pagkain o pagseserbisyo nang walang kinakailangang pantali o takip sa buhok.'},
'VARDA ACT-012':{title:'Mali o Kulang na Uniporme',rule:'Hindi pagsuot ng itinakdang uniporme, apron, ID, o malinis at presentableng kasuotan habang naka-duty.'},
'VARDA ACT-013':{title:'Hindi Malinis na Personal na Gawain sa Food Area',rule:'Maling kalinisan gaya ng paghawak sa mukha o buhok bago pagkain, hindi paghuhugas ng kamay, o unsafe handling.'},
'VARDA ACT-014':{title:'Bawal na Alahas o Personal na Gamit sa Food Area',rule:'Pagsuot ng ipinagbabawal na alahas o paglalagay ng personal na gamit sa food handling o production area.'},
'VARDA ACT-015':{title:'Pagpasok na Hindi Ligtas o Angkop Magtrabaho',rule:'Pagpasok na hindi kayang magtrabaho dahil sa sakit, pagkalasing, sobrang pagod, o kondisyong maaaring makaapekto sa kaligtasan o serbisyo.'},
'VARDA ACT-016':{title:'Hindi Pagkuha o Pagtago ng Food Retention Sample',rule:'Hindi pagkuha o pagtatago ng kinakailangang sample ng pagkain sa loob ng 24–48 oras.'},
'VARDA ACT-017':{title:'Maling Label ng Retention Sample',rule:'Kulang ang pangalan ng item, petsa, oras ng pagluto, oras ng pagsilbi, o pangalan ng responsable sa sample.'},
'VARDA ACT-018':{title:'Hindi Pagtago ng Retention Sample nang 48 Oras',rule:'Maagang pagtatapon ng sample o pagtatago nito sa labas ng nakatalagang retention o chiller zone.'},
'VARDA ACT-019':{title:'Hindi Pag-monitor o Pag-log ng Hot Holding Temperature',rule:'Hindi nasusuri o nala-log sa tamang dalas ang hot holding temperature, o walang aksyon kapag mababa sa standard.'},
'VARDA ACT-020':{title:'Hindi Pag-monitor o Pag-log ng Cold Holding Temperature',rule:'Hindi nasusuri o nala-log ang chiller o freezer temperature, o walang aksyon kapag lampas sa standard.'},
'VARDA ACT-021':{title:'Pagsilbi ng Pagkaing Labas sa Temperature Standard',rule:'Pagsilbi ng pagkain kahit hindi pasado sa hot, cold, o reheating temperature standard.'},
'VARDA ACT-022':{title:'Hindi Pagtapon ng Unsafe o Non-Conforming Food Batch',rule:'Hindi pagtatapon ng batch na bagsak sa temperature, freshness, labeling, o retention standards.'},
'VARDA ACT-023':{title:'Maling FIFO o Stock Rotation',rule:'Hindi paggamit muna sa pinakamatandang stock batay sa delivery o production date.'},
'VARDA ACT-024':{title:'Maling Paraan ng Pag-thaw',rule:'Pag-thaw ng pagkain sa room temperature o sa paraang hindi aprubado.'},
'VARDA ACT-025':{title:'Magkasamang Storage ng Hilaw at Ready-to-Eat Food',rule:'Paglalagay ng hilaw na karne sa ibabaw o kasama ng ready-to-eat food na maaaring magdulot ng contamination.'},
'VARDA ACT-026':{title:'Pagtanggap ng Panis, Tumatagas, o Walang Petsang Delivery',rule:'Pagtanggap ng sangkap na may masamang amoy, madulas, kupas, sirang pakete, tagas, o walang malinaw na expiry date.'},
'VARDA ACT-027':{title:'Hindi Pag-check ng Delivery Temperature',rule:'Hindi pagsuri sa temperatura ng sasakyan o produkto sa pagtanggap ng temperature-sensitive items.'},
'VARDA ACT-028':{title:'Walang Internal Cooking Temperature Check',rule:'Hindi pagsuri o pag-log ng final internal temperature ng manok, giniling na karne, isda, o seafood.'},
'VARDA ACT-029':{title:'Hindi Na-sanitize na Equipment o Utensils',rule:'Hindi lubusang pag-sanitize ng equipment, utensils, o food-contact surfaces na maaaring magdulot ng cross-contamination.'},
'VARDA ACT-030':{title:'Hindi Paghahanda ng Retention Containers Bago Service',rule:'Hindi paghahanda ng retention containers sa pre-service setup kaya maaaring hindi makakuha ng sample.'},
'VARDA ACT-031':{title:'Hindi Pag-report ng Peste o Sira sa Pasilidad',rule:'Hindi pag-report ng nakitang peste o pinsala sa pasilidad habang ginagawa ang arrival inspection.'},
'VARDA ACT-032':{title:'Hindi Ligtas na Gas Line o Equipment Check',rule:'Hindi pagtiyak na ligtas ang gas lines, burners, ovens, bain-maries, o critical equipment bago mag-operate.'},
'VARDA ACT-033':{title:'Hindi Paglinis ng Grease Trap o Waste Area',rule:'Hindi tamang paglinis o pamamahala ng grease trap, waste area, o basurahan na nagdudulot ng sanitation o pest risk.'},
'VARDA ACT-034':{title:'Maling Waste Segregation',rule:'Hindi paghihiwalay ng nabubulok, di-nabubulok, at recyclable waste ayon sa protocol ng paaralan.'},
'VARDA ACT-035':{title:'Hindi Pagpapanatiling Malinis ng Serving o Table Area',rule:'Hindi pagpapanatiling malinis ng table, serving area, o customer-facing area ng front staff.'},
'VARDA ACT-036':{title:'Hindi Agarang Pagsuri sa Customer Concern',rule:'Hindi agad pagsasagawa ng on-site assessment ng management o assigned staff kapag may natanggap na concern.'},
'VARDA ACT-037':{title:'Hindi Pag-backtrack ng POS o Online Records',rule:'Hindi pagsusuri ng POS transaction o online records sa complaint investigation kahit kinakailangan.'},
'VARDA ACT-038':{title:'Hindi Paghambing ng Retention Sample sa Feedback',rule:'Hindi pagsusuri at paghambing ng food retention sample sa iniulat na concern ng customer.'},
'VARDA ACT-039':{title:'Pag-iwas, Pagbalewala, o Pag-antala sa Complaint',rule:'Pag-iwas o pag-antala sa complaint handling sa halip na maayos na idokumento at i-escalate.'},
'VARDA ACT-040':{title:'Kulang na Patunay sa Complaint Resolution',rule:'Pagsasara ng complaint case nang walang kinakailangang data, physical, customer, o audit proof.'},
'VARDA ACT-041':{title:'Hindi Nakumpleto ang Opening SOP',rule:'Hindi pagkumpleto ng kinakailangang opening tasks sa kitchen o front-of-house bago magsimula ang serbisyo.'},
'VARDA ACT-042':{title:'Hindi Pag-check ng Inventory para sa Panis o Label',rule:'Hindi pagsuri ng perishable inventory para sa pagkapanis o tamang label habang opening.'},
'VARDA ACT-043':{title:'Hindi Naka-activate ang POS o Hindi Na-check ang Connection',rule:'Hindi pagbukas o pag-check sa connectivity ng UTAK POS o kinakailangang system bago service.'},
'VARDA ACT-044':{title:'Hindi Nabilang o Na-verify ang Opening Cash Float',rule:'Hindi pagbilang o pagtiyak sa cash float at denominations sa opening.'},
'VARDA ACT-045':{title:'Hindi Updated ang Menu o Digital Signage',rule:'Hindi pag-update ng digital signage o menu board ayon sa mga aprubadong produkto.'},
'VARDA ACT-046':{title:'Food Display na Walang Tamang Proteksyon',rule:'Pag-display ng pagkain nang walang wastong sneeze guard o proteksyon kung kinakailangan.'},
'VARDA ACT-047':{title:'Hindi Ligtas na Kitchen Power-Down',rule:'Hindi ligtas na pagsara ng pilot lights o main gas valves sa closing.'},
'VARDA ACT-048':{title:'Hindi Nakumpleto ang Closing SOP',rule:'Hindi pagkumpleto ng waste, cash reconciliation, facility sweep, locks, o closing checklist.'},
'VARDA ACT-049':{title:'Hindi Nakumpleto ang Facility Security Sweep',rule:'Hindi pagsasagawa ng final check sa dining hall, pinto, bintana, at kandado sa closing.'},
'VARDA ACT-050':{title:'Napabayaang Equipment Maintenance',rule:'Hindi paggawa ng daily, weekly, o deep maintenance para sa burners, chillers, bain-maries, o POS hardware.'},
'VARDA ACT-051':{title:'Hindi Agarang Pag-report ng Cash Variance',rule:'Hindi agarang pag-report kapag hindi tugma ang physical cash sa POS o end-of-day report.'},
'VARDA ACT-052':{title:'Mali o Kulang na Sales Report',rule:'Kulang o mali ang top-selling items, sales breakdown, LO reports, o iba pang kinakailangang sales data.'},
'VARDA ACT-053':{title:'Operational Expense na Walang Sapat na Resibo',rule:'Expense o budget liquidation na walang official receipt o kinakailangang supporting document.'},
'VARDA ACT-054':{title:'Maling Pagproseso ng Transaksyon',rule:'Maling pagproseso ng cash o digital payment, o transaksyong walang wastong POS record.'},
'VARDA ACT-055':{title:'Hindi Pagpapanatili ng Tamang Online Records',rule:'Kulang, hindi ma-access, o hindi maayos ang transaction o online records na kailangan sa imbestigasyon.'},
'VARDA ACT-056':{title:'Hindi Pangunguna ng Branch Manager sa CPAR',rule:'Hindi pangunguna ng branch manager o store supervisor sa CPAR o corrective response para sa audit o customer findings.'},
'VARDA ACT-057':{title:'Kulang na Photo Logs o Retraining Signatures',rule:'Hindi pagpapanatili ng manager o leader ng audit-ready photo logs o pirma sa retraining.'},
'VARDA ACT-058':{title:'Hindi Pagsagawa ng Evaluation o Pamamahala ng Schedule',rule:'Hindi pag-evaluate ng performance o maayos na paggawa ng schedule na nagdudulot ng operational gaps.'},
'VARDA ACT-059':{title:'Hindi Agarang Pag-abiso sa National Management',rule:'Hindi agarang pag-escalate sa National Management ng critical operational, FSQA, o customer issue.'},
'VARDA ACT-060':{title:'Hindi Pamamahala ng Head Chef sa Production Logs',rule:'Hindi pagpapanatili ng head chef o cook ng kitchen inventory, production logs, o LO reports.'},
'VARDA ACT-061':{title:'Hindi Pagsunod sa Menu Plan o Recipe Standard',rule:'Hindi pagsunod sa Varda food quality o presentation dahil sa hindi awtorisadong pagbabago sa recipe o menu.'},
'VARDA ACT-062':{title:'Kulang ang Kinakailangang Bahagi ng CPAR',rule:'Kulang ang CPAR sa acknowledgment date, proof of resolution, preventive action, o sign-off.'},
'VARDA ACT-063':{title:'CPAR na Walang Review ng National Retail Head',rule:'Pagsumite ng CPAR sa labas nang walang kinakailangang review o sign-off ng National Retail Head.'},
'VARDA ACT-064':{title:'Paggamit ng Luma o Uncontrolled na Manual/SOP',rule:'Paggamit ng lumang manual, SOP, o form sa halip na kasalukuyang bersyon.'},
'VARDA ACT-065':{title:'Hindi Pag-review ng Manual/SOP Kada 6 Buwan',rule:'Hindi pagsagawa ng assigned department ng kinakailangang anim-na-buwang review ng manual o policies.'},
'VARDA ACT-066':{title:'Pagsara ng Imbestigasyon nang Walang Patunay',rule:'Pagsasara ng imbestigasyon nang walang kinakailangang data, physical, customer, o audit proof.'},
'VARDA ACT-067':{title:'Hindi Pagpreserba ng Ebidensya',rule:'Pagkawala o hindi pag-iingat ng retention samples, photos, logs, o records na kailangan sa imbestigasyon.'},
'VARDA ACT-068':{title:'Hindi Awtorisadong Pag-delete o Pagbago ng Records',rule:'Pag-delete o pagbabago ng V-SCORE, POS, audit, o evidence records nang walang pahintulot.'},
'VARDA ACT-069':{title:'Hindi Pakikipagtulungan sa Imbestigasyon',rule:'Pagtanggi na magbigay ng pahayag, ebidensya, o tapat na kooperasyon sa awtorisadong imbestigasyon.'},
'VARDA ACT-070':{title:'Paghihiganti sa Reporter o Witness',rule:'Pananakot, paghihiganti, o masamang aksyon laban sa staff na nag-report o nagsilbing witness.'},
'VARDA ACT-071':{title:'Pag-upload ng Hindi Kaugnay na Ebidensya',rule:'Photo o file na walang kaugnayan, nakalilinlang, recycled, o hindi konektado sa aktuwal na incident o task.'},
'VARDA ACT-072':{title:'Paggamit ng Account ng Ibang Empleyado',rule:'Pag-login, pag-post, pag-acknowledge ng memo, o pagsusumite gamit ang account ng ibang empleyado.'},
'VARDA ACT-073':{title:'Hindi Pagprotekta sa Account Credentials',rule:'Pagbabahagi ng password, paglalantad ng credential slip, o hindi pagprotekta sa account access.'},
'VARDA ACT-074':{title:'Pag-bypass sa Required Photo o Checklist',rule:'Pagtangkang mag-close ng shift, kumpletuhin ang task, o mag-file ng record nang walang kinakailangang photo o checklist proof.'},
'VARDA ACT-075':{title:'Maling Paggamit ng Chat o News Feed',rule:'Pag-post ng offensive, walang kaugnayan, confidential, misleading, o harmful content sa app chat o news feed.'},
'VARDA ACT-076':{title:'Peke o Malisyosong Report Laban sa Empleyado',rule:'Pagsumite ng concern o violation report na alam na peke o ginawa nang may masamang layunin.'},
'VARDA ACT-077':{title:'Hindi Pagkumpleto ng Tinanggap na Mission',rule:'Pagtanggap ng mission o task na may due date ngunit hindi ito pagkumpleto nang walang katanggap-tanggap na dahilan.'},
'VARDA ACT-078':{title:'Hindi Makatwirang Pagtanggi sa Mission',rule:'Pagtanggi sa assigned mission nang walang makatwirang operational, health, o schedule basis.'},
'VARDA ACT-079':{title:'Hindi Pag-upload ng Proof sa Shared Tasklist',rule:'Pag-post o pagkumpleto ng shared tasklist nang walang kinakailangang proof photo o completion details.'},
'VARDA ACT-080':{title:'Hindi Pagkumpleto ng Required Training',rule:'Hindi pagkumpleto ng required training module pagkatapos ng deadline nang walang valid na dahilan.'},
'VARDA ACT-081':{title:'Hindi Awtorisadong Public Communication o Escalation',rule:'Pakikipag-ugnayan sa labas, partner, o school official gamit ang hindi awtorisadong channel na maaaring makasira sa Varda.'},
'VARDA ACT-082':{title:'Pag-post ng Hindi Aprubadong Brand o Site Material',rule:'Pag-post ng content gamit ang Varda o partner-school branding nang walang approval o sa paraang mali ang representasyon.'},
'VARDA ACT-083':{title:'Hindi Propesyonal na Pagbati o Pagtulong sa Customer',rule:'Pagbalewala sa customer, hindi pagsagot sa policy inquiries, o hindi pagbibigay ng pangunahing magalang na serbisyo.'},
'VARDA ACT-084':{title:'Pagbubunyag ng Confidential Information',rule:'Pagbabahagi nang walang pahintulot ng company records, complaints, audit documents, employee records, o financial data.'},
'VARDA ACT-085':{title:'Kilos na Nagdudulot ng Malubhang Safety, Legal, o Reputational Risk',rule:'Anumang hindi nakalistang kilos na nagdudulot ng seryosong panganib sa food o employee safety, legal compliance, customer trust, o reputasyon ng Varda.'},
'VARDA ACT-086':{title:'Hindi Pag-record ng Time-In o Time-Out sa UTAK POS',rule:'Hindi maayos na pag-record ng time-in o time-out sa UTAK POS nang walang valid na dahilan, kaya kulang o hindi mapatunayan ang attendance record.'}
};
